### ISSUE TITLE
Error of Jetson Copilet with RAG

### ISSUE THREAD

**Issue by ManaEdgeAI** [NVIDIA-AI-IOT/jetson-copilot#4]
I can run Jetson Copilet without RAG correctly on Orin, but always with following troubles for all created Indexs, such as from single file (   jetson_orin_nano_devkit_carrier_board_specification_sp.pdf ), single URL ( https://docs.nvidia.com/moj/nvstreamer/moj-nvstreamer.html ) etc. I selected "llama3:latest" as the local embedding model.

Should I need to modify the chunk parameters ? 

``
Instruction: Use the previous chat history, or the context above, to interact and help the user.
INFO:root:>>> RAG enabled:
2024-06-20 07:49:21.459 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/opt/jetson_copilot/app/app.py", line 153, in <module>
    message = st.write_stream(model_res_generator(prompt))
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/elements/write.py", line 167, in write_stream
    for chunk in stream:  # type: ignore
  File "/opt/jetson_copilot/app/app.py", line 123, in model_res_generator
    response_stream = st.session_state.chat_engine.stream_chat(prompt)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/chat_engine/context.py", line 198, in stream_chat
    context_str_template, nodes = self._generate_context(message)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/chat_engine/context.py", line 110, in _generate_context
    nodes = self._retriever.retrieve(message)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py", line 223, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/base/base_retriever.py", line 242, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py", line 223, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 101, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 177, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/vector_stores/simple.py", line 369, in query
    top_similarities, top_ids = get_top_k_embeddings(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/query/embedding_utils.py", line 30, in get_top_k_embeddings
    similarity = similarity_fn(query_embedding_np, emb)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/base/embeddings/base.py", line 57, in similarity
    product = np.dot(embedding1, embedding2)
ValueError: shapes (1024,) and (4096,) not aligned: 1024 (dim 0) != 4096 (dim 0)
``

**Comment by tokk-nv** [comment]
It sounds like you have selected "**llama3:latest**" for the local embedding model.
Please make sure you select "**mxbai-embed-large:latest**" for the local embedding model, and create a new index.

![image](https://github.com/NVIDIA-AI-IOT/jetson-copilot/assets/25759564/d5ac5322-739d-4235-9ec9-8d6ccdf4666a)

**Comment by ManaEdgeAI** [comment]
When I select "mxbai-embed-large:latest" , show the error message as below, that's why I select llama3:latest for trial。

![2024-06-21 11-11-52屏幕截图](https://github.com/NVIDIA-AI-IOT/jetson-copilot/assets/171816404/c3483096-6e1a-47fc-ab36-ac9467e053d6)

But evernthing is correct when I duplicate the procedure at Xavier on JP 5.1.3 by using dustynv/jetrag:r35.4.1 image.

**Comment by ManaEdgeAI** [comment]
Thanks, issue solved!

**Comment by tokk-nv** [comment]
Thank you for letting me know it's solved.

It's actually a known issue that sometimes the OpenAI embedding model is left selected.
Will try to address it in the future, but the workaround for now is to always click the drop-down select menu and explicitly select the "mxbai-embed-large" model.
